// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "b92859ea-7dce-4f56-8b65-b0e3d6cb2ded";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onColor1Change();
void onColor2Change();
void onColor3Change();
void onTreeColorChange();
void onTreePlasmaChange();
void onTreeBlendChange();
void onTreeConfettiChange();
void onTreeFireChange();
void onTreeLightningChange();
void onTreePatternChange();
void onTreeRainbowChange();
void onTreeSacnChange();
void onTreeSweepChange();
void onTreeGlitterChange();
void onBpmChange();
void onNumLedsOnPin2Change();
void onNumLedsOnPin3Change();
void onNumLedsOnPin4Change();
void onNumLedsOnPin5Change();
void onRotateSpeedChange();
void onUniverseChange();

CloudColor color1;
CloudColor color2;
CloudColor color3;
CloudColoredLight tree_color;
CloudColoredLight tree_plasma;
CloudDimmedLight tree_blend;
CloudDimmedLight tree_confetti;
CloudDimmedLight tree_fire;
CloudDimmedLight tree_lightning;
CloudDimmedLight tree_pattern;
CloudDimmedLight tree_rainbow;
CloudDimmedLight tree_sacn;
CloudDimmedLight tree_sweep;
CloudLight tree_glitter;
int bpm;
int numLedsOnPin2;
int numLedsOnPin3;
int numLedsOnPin4;
int numLedsOnPin5;
int rotateSpeed;
int universe;
CloudTime runningTime;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(color1, READWRITE, ON_CHANGE, onColor1Change);
  ArduinoCloud.addProperty(color2, READWRITE, ON_CHANGE, onColor2Change);
  ArduinoCloud.addProperty(color3, READWRITE, ON_CHANGE, onColor3Change);
  ArduinoCloud.addProperty(tree_color, READWRITE, ON_CHANGE, onTreeColorChange);
  ArduinoCloud.addProperty(tree_plasma, READWRITE, ON_CHANGE, onTreePlasmaChange);
  ArduinoCloud.addProperty(tree_blend, READWRITE, ON_CHANGE, onTreeBlendChange);
  ArduinoCloud.addProperty(tree_confetti, READWRITE, ON_CHANGE, onTreeConfettiChange);
  ArduinoCloud.addProperty(tree_fire, READWRITE, ON_CHANGE, onTreeFireChange);
  ArduinoCloud.addProperty(tree_lightning, READWRITE, ON_CHANGE, onTreeLightningChange);
  ArduinoCloud.addProperty(tree_pattern, READWRITE, ON_CHANGE, onTreePatternChange);
  ArduinoCloud.addProperty(tree_rainbow, READWRITE, ON_CHANGE, onTreeRainbowChange);
  ArduinoCloud.addProperty(tree_sacn, READWRITE, ON_CHANGE, onTreeSacnChange);
  ArduinoCloud.addProperty(tree_sweep, READWRITE, ON_CHANGE, onTreeSweepChange);
  ArduinoCloud.addProperty(tree_glitter, READWRITE, ON_CHANGE, onTreeGlitterChange);
  ArduinoCloud.addProperty(bpm, READWRITE, ON_CHANGE, onBpmChange);
  ArduinoCloud.addProperty(numLedsOnPin2, READWRITE, ON_CHANGE, onNumLedsOnPin2Change);
  ArduinoCloud.addProperty(numLedsOnPin3, READWRITE, ON_CHANGE, onNumLedsOnPin3Change);
  ArduinoCloud.addProperty(numLedsOnPin4, READWRITE, ON_CHANGE, onNumLedsOnPin4Change);
  ArduinoCloud.addProperty(numLedsOnPin5, READWRITE, ON_CHANGE, onNumLedsOnPin5Change);
  ArduinoCloud.addProperty(rotateSpeed, READWRITE, ON_CHANGE, onRotateSpeedChange);
  ArduinoCloud.addProperty(universe, READWRITE, ON_CHANGE, onUniverseChange);
  ArduinoCloud.addProperty(runningTime, READ, 5 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
